### ISSUE TITLE
ReferenceError: msg is not defined

### ISSUE THREAD

**Issue by nblackburn** [brunch/deppack#39]
`msg` is undefined as it's dependant on `data` existing to be defined.

``` bash
brunch watch --server

29 Jul 16:07:45 - info: application started on http://localhost:3333/
29 Jul 16:07:49 - info: compiling
29 Jul 16:07:55 - info: compiling.
/Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/deppack/lib/resolve.js:68
  err = new Error(msg);
                  ^

ReferenceError: msg is not defined
  at glob.then.mods.forEach.friendlyRequireError (/Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/deppack/lib/resolve.js:68:19)
  at /Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/deppack/lib/resolve.js:90:17
  at /Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/browser-resolve/index.js:265:24
  at /Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/resolve/lib/async.js:55:18
  at load (/Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/resolve/lib/async.js:92:31)
  at /Users/[USERNAME]/Workspace/[PROJECT_NAME]/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:82:15)
```
- **File**: [lib/resolve.js](https://github.com/brunch/deppack/blob/master/lib/resolve.js#L68)
- **Line**: 68

**Comment by lukerollans** [comment]
@paulmillr I'm getting a similar issue while working on a Phoenix app.

Do you have a timeline for when this will be out on npm?

```
[info] Running Sightseer.Endpoint with Cowboy using http://localhost:4000
/Users/lukerollans/code/sightseer/node_modules/deppack/lib/resolve.js:68
  err = new Error(msg);
                  ^

ReferenceError: msg is not defined
  at friendlyRequireError (/Users/lukerollans/code/sightseer/node_modules/deppack/lib/resolve.js:68:19)
  at browserResolve (/Users/lukerollans/code/sightseer/node_modules/deppack/lib/resolve.js:90:17)
  at /Users/lukerollans/code/sightseer/node_modules/browser-resolve/index.js:265:24
  at /Users/lukerollans/code/sightseer/node_modules/resolve/lib/async.js:46:14
  at process (/Users/lukerollans/code/sightseer/node_modules/resolve/lib/async.js:173:43)
  at ondir (/Users/lukerollans/code/sightseer/node_modules/resolve/lib/async.js:188:17)
  at load (/Users/lukerollans/code/sightseer/node_modules/resolve/lib/async.js:69:43)
  at onex (/Users/lukerollans/code/sightseer/node_modules/resolve/lib/async.js:92:31)
  at /Users/lukerollans/code/sightseer/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by nblackburn** [comment]
@lukerollans It's fixed, just waiting for it to be released which i imagine will fall in line with the next brunch release.

**Comment by paulmillr** [comment]
pushed
